site_name: Proyecto de Alejandro Salmerón Rodríguez
site_url: https://4065662.github.io/proyecto-mkdocs/
theme:
  name: material

nav:
  - Inicio: index.md
  - Información sobre mí: formacion.md
  - Mi página de proyectos propios: proyectos.md
  - Mi página de contacto: contacto.md


